#pragma once
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sample_Controller */

#ifndef _Included_sample_Controller
#define _Included_sample_Controller
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     sample_Controller
	* Method:    minimax
	* Signature: ([Ljava/lang/Object;)I
	*/
	JNIEXPORT jint JNICALL Java_sample_Controller_minimax
		(JNIEnv *env, jobject, jobjectArray);

	/*
	* Class:     sample_Controller
	* Method:    random
	* Signature: ([Ljava/lang/Object;)I
	*/
	JNIEXPORT jint JNICALL Java_sample_Controller_random
		(JNIEnv *env, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
